# Generated by Django 4.2.3 on 2024-01-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescuenetApp', '0002_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area_of_expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rescuenetApp.areaofexpertise'),
        ),
    ]
