# Generated by Django 4.2.3 on 2024-02-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuenetApp', '0006_disaster_agencygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencygroup',
            name='dissolution_time',
            field=models.DateTimeField(null=True),
        ),
    ]
